### ISSUE TITLE
bug in last commit

### ISSUE THREAD

**Issue by geeksesi** [amovah/speedster#6]
first open program : 
![2019-02-03-18 32 11](https://user-images.githubusercontent.com/28778964/52178313-14689080-27e2-11e9-8395-02d7f9fbf634.png)

when go on incomplete download and click on of them just watch a blank page : 
![2019-02-03-18 34 30](https://user-images.githubusercontent.com/28778964/52178334-5eea0d00-27e2-11e9-81bb-8afc41679064.png)

in console : ( log file ) 
[-1549206305365.log](https://github.com/amovah/speedster/files/2825621/-1549206305365.log)

**Comment by amovah** [comment]
app.css is only available in production enviroment. so it's not bug.

and for second things, according to your log file, it semes you added the this url before the connection feature. if it's possible for you, remove the download then add it again. I think your problem will be solved. if you confirm I wanna close this issue

**Comment by geeksesi** [comment]
ok. i think it's problem.
and i have more question.
when i don't have old version. how can i remove my old links ? an what about newer update with new tools ?

**Comment by amovah** [comment]
#7dc2463
