### ISSUE TITLE
Handling command line Arguments

### ISSUE THREAD

**Issue by thisismehdi** [amovah/speedster#7]
I was trying to make an extension for the program but I ran to that fact the program doesn't catch any argument from the command line 
plz add the support 
-----------
به فارسشم بگم که انگیسم خوب نیست داشتم با استفاده از این 
https://add0n.com/external-application-button.html?from=context
یه اد ان میساختم برای برنامه ساختن که نه تنظیم میکردم درواقع 
اما مشکل اینه که برنامه ارگومان نمیگیره

**Comment by geeksesi** [comment]
سلام.
بخش سوکت رو نگاه کن.
فکر کنم کارت رو راه بندازه.
https://github.com/amovah/speedster/blob/master/src/sockets.js
( برای ساخت افزونه می تونی به جای استفاده از یه ارگومان کامندلاین به سوکت درخواست بفرستی )

**Comment by amovah** [comment]
I'm very glad that you are using and helping me in this application. I have news for you, I've developed the plugins for browser (only for firefox tested). I'm just waiting for new icon to release browser plugin.

And about your question, there is websocket server, so you can easily connect to it, and control the app with that simple socket events.

**Comment by thisismehdi** [comment]
Thank you for putting me on news it's sound great and I'm looking forward to next release

**Comment by amovah** [comment]
@thisismehdi I released v2.2.0. you can download from release page.
